# Site settings

# Setup
title:            Entelligently
tagline:          'Connecting people and buildings to improve performance and comfort'
description:      'entelligently® improves the comfort of building users & reduces carbon emissions. The more you use entelligently® the more intelligent your building becomes.'
keywords:         'energy, IOT, comfort, building management, Entelligently, comfort management, building comfort management, smart buildings, smart office'
url:              ''
baseurl:          ''
twitter_username: Entelligently

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
