# Site settings

# Setup
title:            Entelligently
tagline:          'Automated, intelligent, workplace environment control. Improve employee comfort and productivity.'
description:      'entelligently® improves employee wellbeing & helps manage your energy sustainability. The more you use entelligently® the more intelligent your building becomes.'
keywords:         'energy, IOT, comfort, building management, Entelligently, comfort management, building comfort management, smart buildings, smart office, workplace management'
url:              ''
baseurl:          ''
twitter_username: Entelligently

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

paginate: 5
paginate_path: blog/page:num
  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
